CREATE TABLE wordList (
    id SERIAL PRIMARY KEY,
    word VARCHAR(50) NOT NULL,
);

INSERT INTO wordList (word)
            values ('run'),
            ('rice'),
            ('rat'),
            ('carrot'),
            ('bird'),
            ('four'),
            ('bear'),
            ('deer'),
            ('bread'),
            ('crayons'),
            ('drive'),
            ('freckles'),
            ('grandpa'),
            ('prince'),
            ('tree'),
            ('rabbit'),
            ('really'),
            ('berry'),
            ('blueberry'),
            ('guitar'),
            ('sit'),
            ('soup'),
            ('salt'),
            ('dance'),
            ('pencil'),
            ('listen'),
            ('bus'),
            ('horse'),
            ('yes'),
            ('scoop'),
            ('slow'),
            ('smell'),
            ('snail'),
            ('spoon'),
            ('stop'),
            ('swim');
    
